name: Build a Raspberry Pi OS image

on:
  push:
    branches:
      - "smartmeter-datacollector**"
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-raspberrypi-image:
    runs-on: ubuntu-24.04-arm

    name: Build a Raspberry Pi OS image
    steps:
      - uses: actions/checkout@v4
      - name: Prepare build environment
        run: |
          sudo apt-get update
          sudo apt-get -y install coreutils quilt parted qemu-user-binfmt debootstrap zerofree zip \
          dosfstools e2fsprogs libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc \
          gpg pigz xxd arch-test bmap-tools kmod

      - name: Build the Raspberry Pi OS image
        run: sudo ./build.sh

      - name: Archive the Raspberry Pi OS image
        uses: actions/upload-artifact@v4
        with:
          name: smartmeter-rpi-demo-image
          path: deploy/*.zip
